### ISSUE TITLE
Add additional REST routes

### ISSUE THREAD

**Issue by tortillaj** [ProboCI/probo-asset-receiver#7]
@lliss We need additional routes for: 
1. Listing assets from a bucket at `GET /buckets/:bucketName/assets` with at minimum asset id and asset file name, but asset size might be nice too, if available
2. Deleting an asset from a bucket at `DEL /buckets/:bucketName/assets/:assetName`

Edited 2016-03-02 by @lliss:  Change the DEL endpoint.

**Comment by tortillaj** [comment]
@lliss Hoping you haven't gotten too far to ask a quick addition. Can we stream the bucket assets, very similar to how we are streaming [`listBucketTokens`](https://github.com/ProboCI/probo-asset-receiver/blob/master/lib/Server.js#L166)?

**Comment by lliss** [comment]
@tortillaj Yes we can.
